version: '3.9'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules     # Volumen anónimo para que persista internamente
      - ./front-end:/app:cached
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - turnos-net


  backend:
    build:
      context: ./back-end
    volumes:
      - ./back-end:/app
    env_file: .env
    ports:
      - "5050:5050"
    depends_on:
      - db
    networks:
      - turnos-net

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - turnos-net

volumes:
  postgres_data:

networks:
  turnos-net:
