version: '3.9'

services:
  backend:
    build:
      context: ./back-end
    volumes:
      - ./back-end:/app   
    env_file: .env
    ports:
      - "5050:5050"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - turnos-net

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.prod
    ports:
      - "5173:80"
    restart: unless-stopped
    networks:
      - turnos-net

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - turnos-net

volumes:
  postgres_data:

networks:
  turnos-net:
    driver: bridge
