"""agrego campos archivo_blob a Comprobante

Revision ID: 422f60911ad3
Revises: d9d27417c3e8
Create Date: 2025-07-03 18:46:55.745524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422f60911ad3'
down_revision = 'd9d27417c3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprobante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_blob', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprobante', schema=None) as batch_op:
        batch_op.drop_column('archivo_blob')

    # ### end Alembic commands ###
