"""Agrega campo nombre_archivo y mime_type en comprobante

Revision ID: 5ae86caa4668
Revises: 422f60911ad3
Create Date: 2025-07-03 18:54:01.026708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae86caa4668'
down_revision = '422f60911ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprobante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nombre_archivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprobante', schema=None) as batch_op:
        batch_op.drop_column('nombre_archivo')
        batch_op.drop_column('mimetype')

    # ### end Alembic commands ###
