"""migración inicial

Revision ID: 5d7d8e7ddf6a
Revises: 
Create Date: 2025-07-02 15:31:13.620632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7d8e7ddf6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinatario', sa.String(length=255), nullable=True),
    sa.Column('cbu', sa.String(length=64), nullable=True),
    sa.Column('monto_esperado', sa.Float(), nullable=True),
    sa.Column('tiempo_maximo_minutos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bloqueo_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disponibilidad_profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('comprobante_url', sa.String(), nullable=True),
    sa.Column('reservado_temporalmente', sa.Boolean(), nullable=True),
    sa.Column('tiempo_expiracion', sa.DateTime(), nullable=True),
    sa.Column('estado_pago', sa.String(length=20), nullable=True),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference')
    )
    op.create_table('comprobante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('hash_archivo', sa.String(length=64), nullable=False),
    sa.Column('nro_operacion', sa.String(length=32), nullable=True),
    sa.Column('fecha_detectada', sa.DateTime(), nullable=True),
    sa.Column('valido', sa.Boolean(), nullable=True),
    sa.Column('timestamp_carga', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_archivo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comprobante')
    op.drop_table('turno')
    op.drop_table('refresh_token')
    op.drop_table('pago')
    op.drop_table('disponibilidad_profesor')
    op.drop_table('bloqueo_agenda')
    op.drop_table('usuario')
    op.drop_table('profesor')
    op.drop_table('configuracion_pago')
    # ### end Alembic commands ###
