"""agrega campo CBU a Pago

Revision ID: 887ae1cc4250
Revises: 5d7d8e7ddf6a
Create Date: 2025-07-02 15:44:16.807061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887ae1cc4250'
down_revision = '5d7d8e7ddf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cbu', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_column('cbu')

    # ### end Alembic commands ###
