"""agregando modo test a Usuario

Revision ID: bd782c08725e
Revises: 887ae1cc4250
Create Date: 2025-07-03 14:38:02.213536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd782c08725e'
down_revision = '887ae1cc4250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modo_test', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('modo_test')

    # ### end Alembic commands ###
